### ISSUE TITLE
Undefined vairable in cl_rhochi

### ISSUE THREAD

**Issue by wardsimon** [ikibalin/cryspy#3]
https://github.com/ikibalin/cryspy/blob/e2aaf9ea6c2d8f7223928f9950a199931e6fe8b4/cryspy/scripts/cl_rhochi.py#L187

` _h = [self.optional_objs.remove(obj) for obj in reversed(self.mandatory_objs) if (isinstance(x, Diffrn) | isinstance(x, Pd) | isinstance(x, Pd2d))]`

Should be:
`_h = [self.optional_objs.remove(obj) for obj in reversed(self.mandatory_objs) if (isinstance(obj, Diffrn) | isinstance(obj, Pd) | isinstance(obj, Pd2d))]`

**Comment by ikibalin** [comment]
Thanks. It's done.
