### ISSUE TITLE
Iteration error

### ISSUE THREAD

**Issue by wardsimon** [ikibalin/cryspy#4]
https://github.com/ikibalin/cryspy/blob/6b90254997c58319e3ec5f4080ed308ca70c8e60/cryspy/scripts/cl_rhochi.py#L188

Should be:
 `_h = [self.optional_objs.remove(obj) for obj in reversed(self.optional_objs) if ( `

As (Diffrn, Pd, Pd2d) are optional

This is also in the transition-to-version-0.2 branch

**Comment by ikibalin** [comment]
Thanks. It's fixed.
